steps:
  # Run Maven tests (parallel with linting)
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'test-storage'
    entrypoint: 'mvn'
    args: ['test', '-B', '-Dmaven.repo.local=/workspace/.m2/repository']
    waitFor: ['-']  # Run in parallel (don't wait for previous steps)

  # Run linting (Checkstyle) - parallel with tests
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'lint-storage'
    entrypoint: 'mvn'
    args: ['validate', '-B', '-Dmaven.repo.local=/workspace/.m2/repository']
    waitFor: ['-']  # Run in parallel (don't wait for previous steps)

  # Build the application JAR (skip on PR builds)
  - name: 'maven:3.9-eclipse-temurin-17'
    id: 'build-storage'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Skip build on PR builds
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping package step"
          echo "Build validation complete ✓"
          exit 0
        fi
        
        echo "Building application package..."
        mvn package -DskipTests -B -Dmaven.repo.local=/workspace/.m2/repository
    waitFor: ['test-storage', 'lint-storage']  # Wait for tests and linting to complete

  # Build Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only build image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Docker build"
          exit 0
        fi
        
        echo "Building Docker image..."
        docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
                     -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest .

  # Push Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only push image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Docker push"
          exit 0
        fi
        
        echo "Pushing Docker image..."
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest

  # Deploy to Cloud Run - ONLY on main branch
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-storage'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only deploy on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Cloud Run deployment"
          exit 0
        fi
        
        echo "Deploying to Cloud Run..."
        # Service is public (--allow-unauthenticated) for ease of access
        # Authentication is enforced at the application level via Firebase tokens
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --port 8081 \
          --memory 512Mi \
          --cpu 1 \
          --timeout 300 \
          --max-instances 1 \
          --set-env-vars SPRING_PROFILES_ACTIVE=production \
          --set-env-vars FIREBASE_PROJECT_ID=recipe-mgmt-dev \
          --set-env-vars AUTH_ENABLED=true \
          --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=/secrets/firebase-sa.json \
          --set-env-vars FIRESTORE_COLLECTION_RECIPES=recipes \
          --update-secrets "/secrets/firebase-sa.json=firebase-service-account:latest"

# Substitutions for different environments
substitutions:
  _SERVICE_NAME: 'recipe-storage-service'
  _REGION: 'europe-west2'
  _ARTIFACT_REGISTRY_REPO: 'recipe-storage'

# Use faster machine type for builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  # Enable caching for faster builds
  volumes:
  - name: 'm2'
    path: '/workspace/.m2'

# Timeout after 10 minutes (reduced from 20)
timeout: '600s'
