steps:
  # Configure Maven settings to authenticate to Artifact Registry via an access token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'configure-maven-settings'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p /workspace/.m2
        # Generate a minimal Maven settings.xml with server credentials for Artifact Registry
        # This avoids reliance on gcloud's print-settings subcommand which may not be available
        cat > /workspace/.m2/settings.xml <<'SETTINGS'
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>gcp-maven-proxy</id>
              <username>oauth2accesstoken</username>
              <password>@@ACCESS_TOKEN@@</password>
            </server>
          </servers>
        </settings>
        SETTINGS
        # Replace placeholder with runtime access token (error out if token cannot be retrieved)
        # Replace placeholder in the settings.xml with a runtime access token
        sed -i "s|@@ACCESS_TOKEN@@|$(gcloud auth print-access-token)|g" /workspace/.m2/settings.xml
        # Verify the token is populated; fail if empty to avoid unauthorized Maven requests
        if ! grep -q -E "<password>[^<]+</password>" /workspace/.m2/settings.xml; then
          echo "ERROR: settings.xml not properly configured with access token"
          exit 1
        fi

  # Run Maven tests (parallel with linting)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'test-storage'
    entrypoint: 'mvn'
    args: ['-s', '/workspace/.m2/settings.xml', 'test', '-B', '-Dmaven.repo.local=/workspace/.m2/repository']
    waitFor: ['configure-maven-settings']  # Wait for Maven settings to be configured

  # Run linting (Checkstyle) - parallel with tests
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'lint-storage'
    entrypoint: 'mvn'
    args: ['-s', '/workspace/.m2/settings.xml', 'validate', '-B', '-Dmaven.repo.local=/workspace/.m2/repository']
    waitFor: ['configure-maven-settings']  # Wait for Maven settings to be configured

  # Build the application JAR (skip on PR builds)
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-storage'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        
        echo "Building application package..."
        mvn -s /workspace/.m2/settings.xml package -DskipTests -B -Dmaven.repo.local=/workspace/.m2/repository
    waitFor: ['test-storage', 'lint-storage']  # Wait for tests and linting to complete

  # Build Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        
        echo "Building Docker image..."
        docker build -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA} \
                     -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest .

  # Push Docker image - ONLY on main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only push image on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping Docker push"
          exit 0
        fi
        
        echo "Pushing Docker image..."
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:${SHORT_SHA}
        docker push ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest

  # Deploy new image to Cloud Run - ONLY on main branch
  # Note: Only updates the image, other config managed by Terraform
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-storage'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Only deploy on main branch
        if [ "$BRANCH_NAME" != "main" ]; then
          echo "PR build detected (branch: $BRANCH_NAME), skipping deployment"
          exit 0
        fi
        
        echo "Deploying new image to Cloud Run..."
        gcloud run services update ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_SERVICE_NAME}:latest \
          --region ${_REGION}
        
        echo "Deployment complete ✓"

# Substitutions for different environments
substitutions:
  _SERVICE_NAME: 'recipe-storage-service'
  _REGION: 'europe-west2'
  _ARTIFACT_REGISTRY_REPO: 'recipe-storage'

# Use faster machine type for builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  # Enable caching for faster builds
  volumes:
  - name: 'm2'
    path: '/workspace/.m2'

# Timeout after 10 minutes (reduced from 20)
timeout: '600s'
